---
title: Presentations
---

## Topics
- [Aarc 2012 Tcco2 Guideline](aarc-2012-tcco2-guideline.qmd)
- [Aarc Coding Guidelines Procedures](aarc-coding-guidelines-procedures.qmd)
- [Acg 2024 Acute Pancreatitis Guideline](acg-2024-acute-pancreatitis-guideline.qmd)
- [Acute Liver Failure](acute-liver-failure.qmd)
- [Adler Et Al 2017 Comorbidities And Subgroups Of Patients Surviving Severe Acute Hypercapnic Respiratory Failure In The (1)](adler-et-al-2017-comorbidities-and-subgroups-of-patients-surviving-severe-acute-hypercapnic-respiratory-failure-in-the-1.qmd)
- [Adler Et Al. 2017 Comorbidities And Subgroups Of Patients Surviving Severe Acute Hypercapnic Respiratory Failure In Th](adler-et-al-2017-comorbidities-and-subgroups-of-patients-surviving-severe-acute-hypercapnic-respiratory-failure-in-th.qmd)
- [AI For Housestaff](ai-for-housestaff.qmd)
- [Ajrccm 100 Year Anniversary.homeward Bound A Centenary Of Home Mechanical Ventilation](ajrccm-100-year-anniversary-homeward-bound-a-centenary-of-home-mechanical-ventilation.qmd)
- [Ajrccm 2017 Comorbidities Surving Hypercapnia](ajrccm-2017-comorbidities-surving-hypercapnia.qmd)
- [Ajrccm 2021 Aus Pop Prev Hypercapnia](ajrccm-2021-aus-pop-prev-hypercapnia.qmd)
- [Ajrccm 2021 Compensated Hypercapnia Morbidity](ajrccm-2021-compensated-hypercapnia-morbidity.qmd)
- [Ajrccm 2024 Home Niv At Hospital Discharge](ajrccm-2024-home-niv-at-hospital-discharge.qmd)
- [Amia Diagnostic Modeling For Hypercapnia](amia-diagnostic-modeling-for-hypercapnia.qmd)
- [Ann Ats 2013 Can You Sustain What You Need](ann-ats-2013-can-you-sustain-what-you-need.qmd)
- [Annals Ats 2020 Ohs In Bariatric Surg Cohort](annals-ats-2020-ohs-in-bariatric-surg-cohort.qmd)
- [Annats 2014 What Does Weight Have To Do With It](annats-2014-what-does-weight-have-to-do-with-it.qmd)
- [Annats 2015 Var In Home Vent Practice Aus Vs Bc](annats-2015-var-in-home-vent-practice-aus-vs-bc.qmd)
- [Annats Telemonitoring Home Ventilation](annats-telemonitoring-home-ventilation.qmd)
- [Annats Telemonitoring Home Ventilation Supplement](annats-telemonitoring-home-ventilation-supplement.qmd)
- [Annrevmed Niv In Nmd](annrevmed-niv-in-nmd.qmd)
- [Aspire Presentation](aspire-presentation.qmd)
- [Aspre Presention 1 Scratch Pad](aspre-presention-1-scratch-pad.qmd)
- [Aspre Presention 1 Slides](aspre-presention-1-slides.qmd)
- [Ats 2019 Ohs Guidelines](ats-2019-ohs-guidelines.qmd)
- [Ats Mini RIP](ats-mini-rip.qmd)
- [Billing Code Definitions](billing-code-definitions.qmd)
- [Bl Sleep Jc Sept 2022](bl-sleep-jc-sept-2022.qmd)
- [Bl Sleep Jc Sept 2022.pptx After Ks](bl-sleep-jc-sept-2022-pptx-after-ks.qmd)
- [Bmj Orr 2024 Hypercap Rf Prognosis](bmj-orr-2024-hypercap-rf-prognosis.qmd)
- [Boared Review Locke](boared-review-locke.qmd)
- [Brinkman Carbovisor](brinkman-carbovisor.qmd)
- [Bts 2016 Guideline Acute Hypercapnia](bts-2016-guideline-acute-hypercapnia.qmd)
- [Cao Et Al 2024 Roadmap For Advancing A New Subspecialty In Pulmonary Medicine Devoted To Chronic Respiratory Failure](cao-et-al-2024-roadmap-for-advancing-a-new-subspecialty-in-pulmonary-medicine-devoted-to-chronic-respiratory-failure.qmd)
- [Carbon Dioxide Intoxication The Clinical Syndrome, Its Etiology And Management With Particular Reference To The Use Of Mechanical Respirators](carbon-dioxide-intoxication-the-clinical-syndrome-its-etiology-and-management-with-particular-reference-to-the-use-of-mechanical-respirators.qmd)
- [Ccjm 2025 Glp1ra And Pancreatitis](ccjm-2025-glp1ra-and-pancreatitis.qmd)
- [Ccm 2024 Long Term Mortality Rate ICU Patients](ccm-2024-long-term-mortality-rate-icu-patients.qmd)
- [Cell 2018 Neural Control Of Breathing And Co2 Homeostasis](cell-2018-neural-control-of-breathing-and-co2-homeostasis.qmd)
- [Central Line Training 2022 Bl Edits](central-line-training-2022-bl-edits.qmd)
- [Chest 2013 Is Elevated Hco3 Part Of Ohs](chest-2013-is-elevated-hco3-part-of-ohs.qmd)
- [Chest 2018 Initiating Home Vent And Advanced Settings](chest-2018-initiating-home-vent-and-advanced-settings.qmd)
- [Chest 2022 Inpatient Sleep Medicine](chest-2022-inpatient-sleep-medicine.qmd)
- [Chest 2024 Niv For COPD How I Do It](chest-2024-niv-for-copd-how-i-do-it.qmd)
- [Chung Thesis Epidemiology Of Hypercapnic Respiratory Failure](chung-thesis-epidemiology-of-hypercapnic-respiratory-failure.qmd)
- [Comp Phys 2014 Hypovent Piper](comp-phys-2014-hypovent-piper.qmd)
- [Comp Phys Bio 2017 Ph Co2 Reg Evolutionary Importance](comp-phys-bio-2017-ph-co2-reg-evolutionary-importance.qmd)
- [Crd 2024 Hx Of Home Vent](crd-2024-hx-of-home-vent.qmd)
- [Crd 22 0131 Proof](crd-22-0131-proof.qmd)
- [Ctsi Translational Research Trainee Symposium Talk](ctsi-translational-research-trainee-symposium-talk.qmd)
- [Ddavp Clamp](ddavp-clamp.qmd)
- [Determinants Of Co2 Tension Javaheri](determinants-of-co2-tension-javaheri.qmd)
- [Effect Of Cpap On Recurrence Of Afib Hunt Et Al](effect-of-cpap-on-recurrence-of-afib-hunt-et-al.qmd)
- [Ejim 2025 Acute Pancreatitis](ejim-2025-acute-pancreatitis.qmd)
- [Erj 2025 Nasal Masks For Niv](erj-2025-nasal-masks-for-niv.qmd)
- [Err 2023 Qol In Home Ventilation](err-2023-qol-in-home-ventilation.qmd)
- [Ers 2017 Central Disturbances During Sleep](ers-2017-central-disturbances-during-sleep.qmd)
- [Ers 2022 Drive To Breath Niv And COPD](ers-2022-drive-to-breath-niv-and-copd.qmd)
- [Exp Rev Resp 2023 Ev For Niv](exp-rev-resp-2023-ev-for-niv.qmd)
- [Front Med 2022 Monitoring Niv](front-med-2022-monitoring-niv.qmd)
- [Gastroenterology 2024 Pancreatitis Review](gastroenterology-2024-pancreatitis-review.qmd)
- [Graphs For Hypercapnia Hypoxemia](graphs-for-hypercapnia-hypoxemia.qmd)
- [Guyton Asthma Pp](guyton-asthma-pp.qmd)
- [Hypercapnia Computable Phenotype Design](hypercapnia-computable-phenotype-design.qmd)
- [Hypercapnia Diagnostic Modeling Revised](hypercapnia-diagnostic-modeling-revised.qmd)
- [Hypercapnia Jan Trip](hypercapnia-jan-trip.qmd)
- [Hypercapnia Jan Trip.pptx](hypercapnia-jan-trip-pptx.qmd)
- [Hypercapnia Megadeck](hypercapnia-megadeck.qmd)
- [Hypercapnia Pathophysiology](hypercapnia-pathophysiology.qmd)
- [Hypercapnia Poster](hypercapnia-poster.qmd)
- [Hypercapnia Sleep Gr](hypercapnia-sleep-gr.qmd)
- [Hypercapnia Update Jan 2023](hypercapnia-update-jan-2023.qmd)
- [Icslaba Prn And Maintenance](icslaba-prn-and-maintenance.qmd)
- [Ijcp 2022 Hypercapnia Review](ijcp-2022-hypercapnia-review.qmd)
- [Ijerph 2022 OSA And Chronic Respiratory Diseases](ijerph-2022-osa-and-chronic-respiratory-diseases.qmd)
- [IM Noon Conf Respiratory Failure](im-noon-conf-respiratory-failure.qmd)
- [In Defense Of Metaanalysis](in-defense-of-metaanalysis.qmd)
- [J Phys 2017 Lung Effects Of Hypercapnia](j-phys-2017-lung-effects-of-hypercapnia.qmd)
- [Jan 6 Research Meeting](jan-6-research-meeting.qmd)
- [Jcm 2025 Pancreatitis Complication Management](jcm-2025-pancreatitis-complication-management.qmd)
- [Jean Louis Pépin Et Al. 2012 Obesity Hypoventilation Syndrome An Underdiagnosed And Undertreated Condition](jean-louis-p-pin-et-al-2012-obesity-hypoventilation-syndrome-an-underdiagnosed-and-undertreated-condition.qmd)
- [Jhm 2025 Twdfnr Abg For Hypercapnia](jhm-2025-twdfnr-abg-for-hypercapnia.qmd)
- [Jour Resp Review 2022 Mask Systematic Review](jour-resp-review-2022-mask-systematic-review.qmd)
- [June 2023 RIP](june-2023-rip.qmd)
- [K23 RIP](k23-rip.qmd)
- [Ks Sleep Jc Sept 2022.pptx After Ks](ks-sleep-jc-sept-2022-pptx-after-ks.qmd)
- [Lancet 2020 Apec Trial Pancreatitis](lancet-2020-apec-trial-pancreatitis.qmd)
- [Lancet 2020 Apec Trial Pancreatitis Supp](lancet-2020-apec-trial-pancreatitis-supp.qmd)
- [Lancet Resp 2016 Preventing Resp Failure In Obese](lancet-resp-2016-preventing-resp-failure-in-obese.qmd)
- [Locke Aug 19 2024 Srma Project Advice](locke-aug-19-2024-srma-project-advice.qmd)
- [Locke Aug 19 2024 Srma Project Advice.pptx](locke-aug-19-2024-srma-project-advice-pptx.qmd)
- [Locke Aug 2024 Srma Project Advice](locke-aug-2024-srma-project-advice.qmd)
- [Locke Ctsi Translational Research Trainee Symposium Talk](locke-ctsi-translational-research-trainee-symposium-talk.qmd)
- [Locke Disease Definitions](locke-disease-definitions.qmd)
- [Locke Fall 2021 RIP](locke-fall-2021-rip.qmd)
- [Locke Fellow Research](locke-fellow-research.qmd)
- [Locke IM Noon Conf Respiratory Failure](locke-im-noon-conf-respiratory-failure.qmd)
- [Locke Irr 2021 RRT And Code Presentation](locke-irr-2021-rrt-and-code-presentation.qmd)
- [Locke Irr 2022 RRT And Code Presentation](locke-irr-2022-rrt-and-code-presentation.qmd)
- [Locke Loop Diur Hypercapnia](locke-loop-diur-hypercapnia.qmd)
- [Locke Msci](locke-msci.qmd)
- [Locke On Diuresis PGR](locke-on-diuresis-pgr.qmd)
- [Locke On Salt PGR](locke-on-salt-pgr.qmd)
- [Locke Pancreatitis TCC](locke-pancreatitis-tcc.qmd)
- [Locke Patient Preference Scenarios](locke-patient-preference-scenarios.qmd)
- [Locke Pccgr](locke-pccgr.qmd)
- [Locke PGR](locke-pgr.qmd)
- [Locke PGR Co2 Covid ARDS](locke-pgr-co2-covid-ards.qmd)
- [Locke PGR HFPEF](locke-pgr-hfpef.qmd)
- [Locke PGR Hypercapnia](locke-pgr-hypercapnia.qmd)
- [Locke PGR Randomness & Diagnostics](locke-pgr-randomness-diagnostics.qmd)
- [Locke Pleural Fibrosis PGR](locke-pleural-fibrosis-pgr.qmd)
- [Locke Respirolysis](locke-respirolysis.qmd)
- [Locke Respirolysis And Air Hunger](locke-respirolysis-and-air-hunger.qmd)
- [Locke RIP](locke-rip.qmd)
- [Locke Sleep Apnea For Puln Fellows](locke-sleep-apnea-for-puln-fellows.qmd)
- [Locke Summer Bootcamp H2o And Na](locke-summer-bootcamp-h2o-and-na.qmd)
- [Locke Vent Dyssynchrony](locke-vent-dyssynchrony.qmd)
- [Locke Where To Put That Line](locke-where-to-put-that-line.qmd)
- [Meservey Et Al. 2020 Risk Of Readmission And Mortality Following Hospitalization With Hypercapnic Respiratory Failure](meservey-et-al-2020-risk-of-readmission-and-mortality-following-hospitalization-with-hypercapnic-respiratory-failure.qmd)
- [Mm Bl](mm-bl.qmd)
- [Nejm 2014 Python Trial Feeding Pancreatitis](nejm-2014-python-trial-feeding-pancreatitis.qmd)
- [Nejm 2014 Python Trial Feeding Pancreatitis Corr](nejm-2014-python-trial-feeding-pancreatitis-corr.qmd)
- [Nejm 2014 Python Trial Feeding Pancreatitis Supp](nejm-2014-python-trial-feeding-pancreatitis-supp.qmd)
- [Nejm 2021 Pointer Trial](nejm-2021-pointer-trial.qmd)
- [Nejm 2021 Pointer Trial Corr](nejm-2021-pointer-trial-corr.qmd)
- [Nejm 2021 Pointer Trial Editorial](nejm-2021-pointer-trial-editorial.qmd)
- [Nejm 2021 Pointer Trial Supp](nejm-2021-pointer-trial-supp.qmd)
- [Nejm 2022 Waterfall Editorial](nejm-2022-waterfall-editorial.qmd)
- [Nejm 2022 Waterfall Trial Pancreatitis](nejm-2022-waterfall-trial-pancreatitis.qmd)
- [Nejm 2022 Waterfall Trial Pancreatitis Corr](nejm-2022-waterfall-trial-pancreatitis-corr.qmd)
- [Nejm 2022 Waterfall Trial Pancreatitis Supp](nejm-2022-waterfall-trial-pancreatitis-supp.qmd)
- [Nowbar Et Al. 2004 Obesity Associated Hypoventilation In Hospitalized Patients Prevalence, Effects, And Outcome.](nowbar-et-al-2004-obesity-associated-hypoventilation-in-hospitalized-patients-prevalence-effects-and-outcome.qmd)
- [Oaem 2019 Hypercap Cohort 1yr Mort](oaem-2019-hypercap-cohort-1yr-mort.qmd)
- [OSA & Hypoventilation Lit Review](osa-hypoventilation-lit-review.qmd)
- [OSA And Sarcoidosis Lit Review](osa-and-sarcoidosis-lit-review.qmd)
- [OSA As A Risk Factor For Stroke And Death Yaggi Et Al Nejm 2005](osa-as-a-risk-factor-for-stroke-and-death-yaggi-et-al-nejm-2005.qmd)
- [OSA Asthma Lit Review](osa-asthma-lit-review.qmd)
- [OSA Bronchiect Tbm EDAC Lit Review](osa-bronchiect-tbm-edac-lit-review.qmd)
- [OSA In Hypercap Rf](osa-in-hypercap-rf.qmd)
- [OSA VTE & Lung Ca Evidence](osa-vte-lung-ca-evidence.qmd)
- [Overlap Syndrome Evidence Review](overlap-syndrome-evidence-review.qmd)
- [Partial Verification Blurg (incomplete)](partial-verification-blurg-incomplete.qmd)
- [Pe In ICU](pe-in-icu.qmd)
- [PGR](pgr.qmd)
- [PGR Beyond Se And Sp](pgr-beyond-se-and-sp.qmd)
- [PGR Chf And The Lungs](pgr-chf-and-the-lungs.qmd)
- [PGR Extreme Physiology](pgr-extreme-physiology.qmd)
- [PGR Instruments And Mendel](pgr-instruments-and-mendel.qmd)
- [PGR Llms](pgr-llms.qmd)
- [PGR Sims](pgr-sims.qmd)
- [Ph Journal Club Sept 2022](ph-journal-club-sept-2022.qmd)
- [Prospective Study Of OSA And Incident Cad And Hf Gottlieb 2010](prospective-study-of-osa-and-incident-cad-and-hf-gottlieb-2010.qmd)
- [R Phys Neuro 2013 Unanswered Q's Resp Control](r-phys-neuro-2013-unanswered-q-s-resp-control.qmd)
- [Rc 2023 Lower Paco2 In Chr Hypercap Mortality](rc-2023-lower-paco2-in-chr-hypercap-mortality.qmd)
- [Reducing Cv Risk Through Treatment Of OSA Two Methodological Approaches Am Heart J 2016](reducing-cv-risk-through-treatment-of-osa-two-methodological-approaches-am-heart-j-2016.qmd)
- [Renal Replacement Therapy Resp Acidosis](renal-replacement-therapy-resp-acidosis.qmd)
- [Resp Care 2012 Overview Of Hmv In Us](resp-care-2012-overview-of-hmv-in-us.qmd)
- [Resp Care 2024 What Are We Aiming For?](resp-care-2024-what-are-we-aiming-for.qmd)
- [Respirology 2022 Causes Of Hypercapnic Respiratory Failure & In‐hospital Mortality](respirology-2022-causes-of-hypercapnic-respiratory-failure-in-hospital-mortality.qmd)
- [RIP](rip.qmd)
- [RIP Hypercapnia](rip-hypercapnia.qmd)
- [RIP Hypercapnia 2](rip-hypercapnia-2.qmd)
- [Sb261 Most Expensive Hospital Conditions 2017](sb261-most-expensive-hospital-conditions-2017.qmd)
- [SDB And Cardiovascular Disease Cross Sectional Results With Shhs Shahar Et Al](sdb-and-cardiovascular-disease-cross-sectional-results-with-shhs-shahar-et-al.qmd)
- [SDB And Mortality A Prospective Cohort Study Plos Medicine 2009](sdb-and-mortality-a-prospective-cohort-study-plos-medicine-2009.qmd)
- [Sleep Apnea For Pulm Fellows](sleep-apnea-for-pulm-fellows.qmd)
- [Sleep Gr Hypercapnia](sleep-gr-hypercapnia.qmd)
- [Sleep Gr Hypercapnia Slides](sleep-gr-hypercapnia-slides.qmd)
- [Sleep Jc Sept 2022](sleep-jc-sept-2022.qmd)
- [Spiro COPD Noon Conf 2025](spiro-copd-noon-conf-2025.qmd)
- [Thorax 2023 Effect Of Niv On Sleep](thorax-2023-effect-of-niv-on-sleep.qmd)
- [Ueg 2025 Pancreatits Review](ueg-2025-pancreatits-review.qmd)
- [Uspstf Lung Cancer Screening Update](uspstf-lung-cancer-screening-update.qmd)
- [Vonderbank Et Al. 2020 Hypercapnia At Hospital Admission As A Predictor O](vonderbank-et-al-2020-hypercapnia-at-hospital-admission-as-a-predictor-o.qmd)
- [Vr ICU Feasibility Overview](vr-icu-feasibility-overview.qmd)
- [When Does Hypoxemia Become Apparent](when-does-hypoxemia-become-apparent.qmd)
- [When To Stop Proning](when-to-stop-proning.qmd)
