---
title: Locke Where To Put That Line
draft: true
---

## Summary
- PGR: Where to put that line
- Complication rates at various spots
- Reliability of measurement
- Midlines and PIV probably fine:
- PICC vs CVC?
- Incidence and response to malpositioning
- KDIGO and EJ
- Review of complications and utility
- https://www.atsjournals.org/doi/pdf/10.1164/rccm.202103-0685RR
- https://journals.sagepub.com/doi/10.1177/0310057X0803600106
- Response: https://twitter.com/NidaQadirMD/status/1564964701993201664?s20&tM91euLS0cvp2HnMjeNBrQ
- https://twitter.com/kmschramm/status/1567559282085842946?s11&tODYAbT5sHR2uzGqQUzlFjQ

## Slide outline
### Slide 1
- PGR: Where to put that line
- Review of complications and utility
### Slide 2
- Complication rates at various spots
### Slide 3
- Reliability of measurement
### Slide 4
- Midlines and PIV probably fine:
- https://www.atsjournals.org/doi/pdf/10.1164/rccm.202103-0685RR
### Slide 5
- PICC vs CVC?
### Slide 6
- Incidence and response to malpositioning
- https://journals.sagepub.com/doi/10.1177/0310057X0803600106
- Response: https://twitter.com/NidaQadirMD/status/1564964701993201664?s20&tM91euLS0cvp2HnMjeNBrQ
### Slide 7
- KDIGO and EJ
- https://twitter.com/kmschramm/status/1567559282085842946?s11&tODYAbT5sHR2uzGqQUzlFjQ


## Learning objectives
- PGR: Where to put that line
- Complication rates at various spots
- Reliability of measurement
- Midlines and PIV probably fine:
- PICC vs CVC?

## Bottom line / summary
- PGR: Where to put that line
- Complication rates at various spots
- Reliability of measurement
- Midlines and PIV probably fine:
- PICC vs CVC?

## Approach
1. TODO: Outline the initial assessment or decision point.
2. TODO: Outline the next diagnostic or management step.
3. TODO: Outline follow-up or escalation criteria.

## Red flags / when to escalate
- TODO: List red flags that require urgent escalation.

## Common pitfalls
- TODO: Capture common errors or missed steps.

## References
TODO: Add landmark references or guideline citations.

## Slides and assets
- [Presentations/Locke - where to put that line.pptx](../../archive/Presentations/Locke%20-%20where%20to%20put%20that%20line.pptx)

## Source materials
- [Presentations/Locke - where to put that line.pptx](../../archive/Presentations/Locke%20-%20where%20to%20put%20that%20line.pptx)
