---
title: Asthma
draft: true
---

## What this covers
- Definitions
- Diagnosis
- Reliever

## Learning objectives
- Definitions
- Diagnosis
- Reliever

## Bottom line / summary
- Atopy: predisposition to generate IgE vs environmental antigens.
- Mechanisms of asthma:
- severity: determines initial treatment controlled (assess with a std questionnaire)
- ##Management Have asthma action plan:
- If well controlled for 3 weeks (months?

## Approach
1. GINA
2. EPR3
3. ATS/ERS management of severe asthma
4. NEJM 2017 Severe and Difficult to treat asthma
5. type 2 allergic / eosinophilic. Generally assocaited with elevated FeNO and Blood Eosinophilia

## Red flags / when to escalate
- Singulair black box warnings (neuropsychiatric)

## Common pitfalls
- the idea is to avoid a lot of ICS use.

## References
- https://ginasthma.org/gina-reports/
- https://erj.ersjournals.com/content/early/2019/09/19/13993003.00588-2019
- https://www.nejm.org/doi/10.1056/NEJMra1608969
- https://erj.ersjournals.com/content/53/4/1802223
- https://photos.collectednotes.com/photos/5187/b5e55f2e-202f-4e1a-805f-f75bb8532bc2

## Source notes

### Asthma
{{< include "../../include/source-notes/Clinical Practice Notes/asthma.md" >}}

## Source materials
- [Clinical Practice Notes/asthma.md](../../archive/Clinical%20Practice%20Notes/asthma.md)
