---
title: CPET
draft: true
---

## What this covers
- Adequate
- Oxygenation
- Exertional Hypoxemia in COPD

## Learning objectives
- Adequate
- Oxygenation
- Exertional Hypoxemia in COPD
- Exertional Hypoxemia in ILD / pHTN
- Ventilatory Indices
- Patterns

## Bottom line / summary
- Ref: DOI: 10.1002/cphy.c110048
- !alt from https://journal.chestnet.org/article/S0012-3692(20)31415-X/pdf
- 2 ways to calc vo2 that correspond to the 2 systems of bulk flow / convective O2 transport: the respiratory system (measuring directly via douglas bag) and the CV system (measure via blood gasses and Fick Equation).
- VO2 VE (PIO2 - PEO2) Qt (CaO2 - CvO2)
- ##RER (or equiv at cellular level RQ)

## Approach
1. Mechanisms of residual DOE: https://www.atsjournals.org/doi/full/10.1513/AnnalsATS.202004-398FR
2. Grading severity of heart failure (<14L risk of dying of HF > transplant)
3. Lung resection stratification
4. HR 80%+
5. RER > 1.15

## Red flags / when to escalate
- TODO: List red flags that require urgent escalation.

## Common pitfalls
- treated as a non-invasive surrogate of stroke volume (assuming you don't have an extraction of O2 problem)

## References
- https://www.atsjournals.org/doi/full/10.1513/AnnalsATS.202004-398FR
- https://photos.collectednotes.com/photos/5187/8607dc22-d92d-4356-be22-a4f23e56ba8c
- https://journal.chestnet.org/article/S0012-3692(20)31415-X/pdf
- https://photos.collectednotes.com/photos/5187/c04b089a-785b-4a2c-8fa6-508649d21ea0
- https://photos.collectednotes.com/photos/5187/2ee92559-9087-479c-a6fe-a1f4514232b9
- https://photos.collectednotes.com/photos/5187/65d70d99-2e34-492f-9502-cecd019b13f8

## Source notes

### CPET
{{< include "../../include/source-notes/Clinical Practice Notes/cpet.md" >}}

## Source materials
- [Clinical Practice Notes/cpet.md](../../archive/Clinical%20Practice%20Notes/cpet.md)
