---
title: Sleep Disordered Breathing
draft: true
---

## What this covers
- Few snippets from Janet's talk
- Stages of Sleep
- Anatomy

## Learning objectives
- Few snippets from Janet's talk
- Stages of Sleep
- Anatomy
- Equipment
- Respiratory Drive

## Bottom line / summary
- CPAP invented in 1980 (prior to that, OSA treated with tracheostomy)
- Sleepiness a nap is restful vs Fatigue a nap is not necessarily restful vs Alertness ability to respond quickly
- Sleep reasons for BiPAP- higher pressures, pressure intolerance, aerophagia (no titration study, just good documentation)
- Auto-anything EPAP adjusts
- CSA shouldn’t be directly treated with aCPAP

## Approach
1. sleep disordered breathing
2. disorders initiation of sleep (e.g. insomnia, social))
3. disorders of duration of sleep (e.g. hypersonic)
4. disorders of movement (e.g. parasomnias)
5. circadian rhythm disorders (e.g. shift-word)

## Red flags / when to escalate
- Treatment - emergent put someone on CPAP and this occurs via ?mechanism. [ ] look in to this. If this persists, it is called complex sleep apnea.

## Common pitfalls
- Apnea cessation of flow (more than 90% drop) for at least 10 seconds- don't need an arousal or drop in saturation, necessarily
- Of note: in a HST where we don't the neurologic correlate of sleep (no EEG surrogate) so you don't know the time denominator precisely. REI summarizes the events over the total time.

## References
- https://photos.collectednotes.com/photos/5187/3cee551d-5cc3-48ec-bdac-5588d41b59a0
- https://photos.collectednotes.com/photos/5187/29c8eb39-5013-4d9e-af99-9289ddd67cd6
- https://photos.collectednotes.com/photos/5187/5295e833-007b-4089-aa68-cc9af93d4b2e

## Source notes

### Sleep Disordered Breathing
{{< include "../../include/source-notes/Clinical Practice Notes/sleep-disordered-breathing.md" >}}

## Source materials
- [Clinical Practice Notes/sleep-disordered-breathing.md](../../archive/Clinical%20Practice%20Notes/sleep-disordered-breathing.md)
