---
title: Arterial Line
draft: true
---

## What this covers
- Contraindications and complications
- Indication
- Site

## Learning objectives
- Contraindications and complications
- Indication
- Site
- Brachial
- Femoral
- Axillary
- Square Wave test

## Bottom line / summary
- Most commonly, radial artery of non-dominant hand.
- Other options: femoral (central), dorsalis pedis, ulnar, brachial, axillary (central).
- Deep dive to different locations here: https://emcrit.org/pulmcrit/a-line/
- Complication rates: https://journals.lww.com/anesthesia-analgesia/Fulltext/2014/02000/BrachialArteryCatheterizationAnAssessmentof.9.aspx
- Possibly safer than billed?

## Approach
1. arterial BP readings (note: central axillary, fem are more reliable and do not correlate all that well). MAP is still the most reliable indicator (as it is a surrogate for the perfusion pressure)
2. frequent blood gas
3. 2% chlorhexadine skin prep dispensers
4. 2% lidocaine (1-3 ml), with syringe and 25g needle
5. sterile drape

## Red flags / when to escalate
- TODO: List red flags that require urgent escalation.

## Common pitfalls
- arterial BP readings (note: central axillary, fem are more reliable and do not correlate all that well). MAP is still the most reliable indicator (as it is a surrogate for the perfusion pressure)

## References
- https://emcrit.org/pulmcrit/a-line/
- https://journals.lww.com/anesthesia-analgesia/Fulltext/2014/02000/BrachialArteryCatheterizationAnAssessmentof.9.aspx
- https://pubmed.ncbi.nlm.nih.gov/28523028/
- flightbridgeed.com/index.php/blogs/blogs-view/10-artcles/277-well,-i-ll-be-damped-–-how-square-wave-testing-can-assure-accuracy-in-your-hemodynamic-monitoring-interpretations

## Source notes

### Arterial Line
{{< include "../../include/source-notes/Clinical Practice Notes/arterial-line.md" >}}

## Source materials
- [Clinical Practice Notes/arterial-line.md](../../archive/Clinical%20Practice%20Notes/arterial-line.md)
