---
title: Ultrasound
draft: true
---

## What this covers
- Modes
- Physics:
- Goal-directed Echo

## Learning objectives
- Modes
- Physics:
- Goal-directed Echo

## Bottom line / summary
- Ultrasound in the ICU Series, ATS
- (B) brightness mode conventional.
- 2d (spatial) map of reflectiveness
- (M)-mode - aka Time-motion mode: gives information on 1 slide through time..
- Note: Duplex using doppler and b-mode

## Approach
1. pulse wave doppler sends, then listens after (and not sending at the same time) gets artifacts due to Nyquist effect, also only gets motion vector coming directly to probe.
2. Tissue doppler is a variation of this with filters eliminating blood
3. Color wave doppler uses pulses and uses info from each pixel to determine a color (still has limitation of aliasing)
4. continuous wave doppler continuously sending and listening simultaneously (2 elements / piezoelectric elements) no aliasing
5. resolution of ultrasound depends on wavelength (frequency. b/c speed wavelength frequency).

## Red flags / when to escalate
- ##Shock Assessment

## Common pitfalls
- TODO: Capture common errors or missed steps.

## References
- https://www.thoracic.org/professionals/career-development/residents-medical-students/ats-reading-list/adult/ultrasound-in-the-icu.php
- https://www.atsjournals.org/doi/pdf/10.1513/AnnalsATS.202008-948CME
- https://www.thoracic.org/professionals/clinical-resources/critical-care/clinical-education/ultrasound.php

## Source notes

### Ultrasound
{{< include "../../archive/Clinical Practice Notes/ultrasound.md" >}}

## Source materials
- [Clinical Practice Notes/ultrasound.md](../../archive/Clinical%20Practice%20Notes/ultrasound.md)
