---
title: Lactic Acidosis
draft: true
---

## What this covers
- In Sepsis
- When does the body make lactate?
- Why does the body make lactate?

## Learning objectives
- In Sepsis
- When does the body make lactate?
- Why does the body make lactate?
- Why do we care about the lactate in sepsis?
- Other resuscitation targets:
- Methods to help "clear the lactate"
- Fluids

## Bottom line / summary
- Glucose -> Glycolysis -> Pyruvate
- Pyruvate can then go to two paths:
- Path two is chosen when:
- What is the evidence for this?
- beta-blockers lower lactate in sepsis, and albuterol/epinephrine raises lactate in asthma.

## Approach
1. Pyruvate -> Krebs Cycle (requires thiamine) -> Oxidative Phosphorylation
2. Pyruvate -> Lactate -> Cori Cycle or conversion to bicarbonate
3. There is no oxygen for oxidative phosphorylation (e.g. ischemic bowel). This is a marker of hypoperfusion. It is debated whether this contributes at all to lactate production in sepsis. This is the theory that early goal directed therapy is based on (and has subsequently failed to show benefit when compared to modern care that is targeted toward optimizing this).
4. Metabolism is running so fast that glycolysis outpaces aerobic metabolism (e.g. you sprint). This is mediated by B2 adrenergic tone as part of the stress response (glucose increases for the same reason -> mobilize energy stores).
5. UOP, mentation (markers of organ function)

## Red flags / when to escalate
- SEP-1 Federal Mandate: lactate measured within 3 hours in severe sepsis and septic shock. (effect of measuing the lactate? or a marker of better care? - there are almost no "tests" that reduce mortality - tests only influence outcomes based on the actions that result from that test).

## Common pitfalls
- Consider: why does giving crystalloid fluids (which do not carry Oxygen) decrease lactate?

## References
- https://www.nejm.org/doi/10.1056/NEJMc1500327
- https://ccforum.biomedcentral.com/articles/10.1186/s13054-014-0503-3
- https://journals.lww.com/ccmjournal/Abstract/2004/08000/Earlylactateclearanceisassociatedwith.1.aspx
- https://pubmed.ncbi.nlm.nih.gov/30704260/

## Source notes

### Lactic Acidosis
{{< include "../../archive/Clinical Practice Notes/lactic-acidosis.md" >}}

## Source materials
- [Clinical Practice Notes/lactic-acidosis.md](../../archive/Clinical%20Practice%20Notes/lactic-acidosis.md)
