---
title: Tracheostomy
draft: true
---

## What this covers
- Terms
- Overview
- Indications:

## Learning objectives
- Terms
- Overview
- Indications:
- Timing
- Complications
- Equipment:
- Technique

## Bottom line / summary
- But, everyone just calls it tracheostomy
- 3 Types of Surgical Airway Access:
- TracMan JAMA 2013: UK 2004-11, Early (w/n 4 days) vs Late (10 days if still indicated - 50+% ended up not).
- No difference in morality, infections, LOS, duration of mech vent.
- Less sedation in tracheostomy group.

## Approach
1. Tracheotomy: actual procedure of opening the trachea.
2. Tracheostomy: suturing an opening to create a permanent stoma.
3. DCT, DCCT disposable cannula cuffed trach
4. DIC disposable inner cannula
5. XLT extra long trach

## Red flags / when to escalate
- cricothyroidotomy (emergent)
- Cannot change the tube (or re-insert if dislodged) in the first 7 days (need wire / seldinger technique for this time to avoid dissecting into potential space). If it comes out emergently, take it out and ventilate from above.

## Common pitfalls
- Large meta-analyses: Shorter ICU is only consistent effect. (Not mortality). Late tracheostomy many patients don't get trashed. > we don't do well at predicting.
- Cannot change the tube (or re-insert if dislodged) in the first 7 days (need wire / seldinger technique for this time to avoid dissecting into potential space). If it comes out emergently, take it out and ventilate from above.
- Similarly, cuff has to be down (or cuff less trach) prior to eating to avoid compression of the esophagus.

## References
- https://photos.collectednotes.com/photos/5187/11410410-080d-40f3-8cc7-522e2421464a
- https://photos.collectednotes.com/photos/5187/22ddf740-d880-4824-a543-8929df427927

## Source notes

### Tracheostomy
{{< include "../../include/source-notes/Clinical Practice Notes/tracheostomy.md" >}}

## Source materials
- [Clinical Practice Notes/tracheostomy.md](../../archive/Clinical%20Practice%20Notes/tracheostomy.md)
