---
title: Anaphylaxis And Angioedema
draft: true
---

## What this covers
- Angioedema
- Drugs
- Management

## Learning objectives
- Angioedema
- Drugs
- Management
- Anaphylaxis

## Bottom line / summary
- #Anaphylaxis and Angioedema
- Dermal, SQ, mucosal swelling - non pitting.
- vasodilation and increased vascular permeability.
- https://www.sciencedirect.com/science/article/pii/S1323893015302550?via%3Dihub
- ~50 % associated with urticartia

## Approach
1. idiopathic
2. associated with allergic and non-allergic reactions due to antigens (e.g. venom, drugs, foods, pathogens, animals, latex(
3. C1-INH deficiency: inherited or acquired
4. ACEi: never associated with urticaria
5. NSAID: non allergic

## Red flags / when to escalate
- TODO: List red flags that require urgent escalation.

## Common pitfalls
- TODO: Capture common errors or missed steps.

## References
- https://photos.collectednotes.com/photos/5187/06657f72-c3be-4130-92cb-80b80b2a67d5
- https://photos.collectednotes.com/photos/5187/571cbeb7-2efd-4a67-9fcc-56d8c7230ba0
- https://www.sciencedirect.com/science/article/pii/S1323893015302550?via%3Dihub
- https://photos.collectednotes.com/photos/5187/289b7162-b87f-4d79-a3e4-a50195069876
- https://photos.collectednotes.com/photos/5187/66fdd152-802d-4008-a594-4bc42a33ab34
- https://photos.collectednotes.com/photos/5187/44e19f57-acc7-4a53-9b73-f5f64ee961b2
- https://photos.collectednotes.com/photos/5187/f76275de-2577-48e0-bfa5-183952d7f84e
- https://photos.collectednotes.com/photos/5187/ef6e62b0-dc13-4866-abed-8284d39d790d
- https://photos.collectednotes.com/photos/5187/67450424-d1fc-4308-8602-87f1b54ea638
- https://photos.collectednotes.com/photos/5187/67450424-d1fc-4308-8602-87f1b54ea638)#

## Source notes

### Anaphylaxis And Angioedema
{{< include "../../include/source-notes/Clinical Practice Notes/anaphylaxis-and-angioedema.md" >}}

## Source materials
- [Clinical Practice Notes/anaphylaxis-and-angioedema.md](../../archive/Clinical%20Practice%20Notes/anaphylaxis-and-angioedema.md)
